import 'package:review/datatype/datatype.dart';

List<CarsDataCard> _under08 = [
  CarsDataCard(
    price: '1.04',
    carimg: 'img/carscard/second.png',
    engine: 'NCAP: 5*',
    fuel: 'Petrol CNG Diesel',
    drivetype: 'Manual IMT DCT IVT',
    carname: 'Tuscon',
    noofseats: '5 ',
  ),
  CarsDataCard(
    price: '1.04',
    carimg: 'img/carscard/second.png',
    engine: 'NCAP: 5*',
    fuel: 'Petrol CNG Diesel',
    drivetype: 'Manual IMT DCT IVT',
    carname: 'Tuscon',
    noofseats: '5 ',
  ),
  CarsDataCard(
    price: '1.04',
    carimg: 'img/carscard/second.png',
    engine: 'NCAP: 5*',
    fuel: 'Petrol CNG Diesel',
    drivetype: 'Manual IMT DCT IVT',
    carname: 'Tuscon',
    noofseats: '5 ',
  ),
  CarsDataCard(
    price: '1.04',
    carimg: 'img/carscard/second.png',
    engine: 'NCAP: 5*',
    fuel: 'Petrol CNG Diesel',
    drivetype: 'Manual IMT DCT IVT',
    carname: 'Tuscon',
    noofseats: '5 ',
  ),
  CarsDataCard(
    price: '1.04',
    carimg: 'img/carscard/second.png',
    engine: 'NCAP: 5*',
    fuel: 'Petrol CNG Diesel',
    drivetype: 'Manual IMT DCT IVT',
    carname: 'Tuscon',
    noofseats: '5 ',
  ),
  CarsDataCard(
    price: '1.04',
    carimg: 'img/carscard/second.png',
    engine: 'NCAP: 5*',
    fuel: 'Petrol CNG Diesel',
    drivetype: 'Manual IMT DCT IVT',
    carname: 'Tuscon',
    noofseats: '5 ',
  ),
  CarsDataCard(
    price: '1.04',
    carimg: 'img/carscard/second.png',
    engine: 'NCAP: 5*',
    fuel: 'Petrol CNG Diesel',
    drivetype: 'Manual IMT DCT IVT',
    carname: 'Tuscon',
    noofseats: '5 ',
  ),
];

List<CarsDataCard> _under15 = [
  CarsDataCard(
    price: '1.04',
    carimg: 'img/carscard/third.jpeg',
    engine: 'NCAP: 5*',
    fuel: 'Petrol CNG Diesel',
    drivetype: 'Manual IMT DCT IVT',
    carname: 'Tuscon',
    noofseats: '5 ',
  ),
  CarsDataCard(
    price: '1.04',
    carimg: 'img/carscard/third.jpeg',
    engine: 'NCAP: 5*',
    fuel: 'Petrol CNG Diesel',
    drivetype: 'Manual IMT DCT IVT',
    carname: 'Tuscon',
    noofseats: '5 ',
  ),
  CarsDataCard(
    price: '1.04',
    carimg: 'img/carscard/third.jpeg',
    engine: 'NCAP: 5*',
    fuel: 'Petrol CNG Diesel',
    drivetype: 'Manual IMT DCT IVT',
    carname: 'Tuscon',
    noofseats: '5 ',
  ),
  CarsDataCard(
    price: '1.04',
    carimg: 'img/carscard/third.jpeg',
    engine: 'NCAP: 5*',
    fuel: 'Petrol CNG Diesel',
    drivetype: 'Manual IMT DCT IVT',
    carname: 'Tuscon',
    noofseats: '5 ',
  ),
  CarsDataCard(
    price: '1.04',
    carimg: 'img/carscard/third.jpeg',
    engine: 'NCAP: 5*',
    fuel: 'Petrol CNG Diesel',
    drivetype: 'Manual IMT DCT IVT',
    carname: 'Tuscon',
    noofseats: '5 ',
  ),
  CarsDataCard(
    price: '1.04',
    carimg: 'img/carscard/third.jpeg',
    engine: 'NCAP: 5*',
    fuel: 'Petrol CNG Diesel',
    drivetype: 'Manual IMT DCT IVT',
    carname: 'Tuscon',
    noofseats: '5 ',
  ),
  CarsDataCard(
    price: '1.04',
    carimg: 'img/carscard/third.jpeg',
    engine: 'NCAP: 5*',
    fuel: 'Petrol CNG Diesel',
    drivetype: 'Manual IMT DCT IVT',
    carname: 'Tuscon',
    noofseats: '5 ',
  ),
];

List<CarsDataCard> _under25 = [
  CarsDataCard(
    price: '1.04',
    carimg: 'img/carscard/fourth.jpeg',
    engine: 'NCAP: 5*',
    fuel: 'Petrol CNG Diesel',
    drivetype: 'Manual IMT DCT IVT',
    carname: 'Tuscon',
    noofseats: '5 ',
  ),
  CarsDataCard(
    price: '1.04',
    carimg: 'img/carscard/fourth.jpeg',
    engine: 'NCAP: 5*',
    fuel: 'Petrol CNG Diesel',
    drivetype: 'Manual IMT DCT IVT',
    carname: 'Tuscon',
    noofseats: '5 ',
  ),
  CarsDataCard(
    price: '1.04',
    carimg: 'img/carscard/fourth.jpeg',
    engine: 'NCAP: 5*',
    fuel: 'Petrol CNG Diesel',
    drivetype: 'Manual IMT DCT IVT',
    carname: 'Tuscon',
    noofseats: '5 ',
  ),
  CarsDataCard(
    price: '1.04',
    carimg: 'img/carscard/fourth.jpeg',
    engine: 'NCAP: 5*',
    fuel: 'Petrol CNG Diesel',
    drivetype: 'Manual IMT DCT IVT',
    carname: 'Tuscon',
    noofseats: '5 ',
  ),
  CarsDataCard(
    price: '1.04',
    carimg: 'img/carscard/fourth.jpeg',
    engine: 'NCAP: 5*',
    fuel: 'Petrol CNG Diesel',
    drivetype: 'Manual IMT DCT IVT',
    carname: 'Tuscon',
    noofseats: '5 ',
  ),
  CarsDataCard(
    price: '1.04',
    carimg: 'img/carscard/fourth.jpeg',
    engine: 'NCAP: 5*',
    fuel: 'Petrol CNG Diesel',
    drivetype: 'Manual IMT DCT IVT',
    carname: 'Tuscon',
    noofseats: '5 ',
  ),
  CarsDataCard(
    price: '1.04',
    carimg: 'img/carscard/fourth.jpeg',
    engine: 'NCAP: 5*',
    fuel: 'Petrol CNG Diesel',
    drivetype: 'Manual IMT DCT IVT',
    carname: 'Tuscon',
    noofseats: '5 ',
  ),
];

List<CarsDataCard> _under50 = [
  CarsDataCard(
    price: '1.04',
    carimg: 'img/carscard/fifth.jpeg',
    engine: 'NCAP: 5*',
    fuel: 'Petrol CNG Diesel',
    drivetype: 'Manual IMT DCT IVT',
    carname: 'Tuscon',
    noofseats: '5 ',
  ),
  CarsDataCard(
    price: '1.04',
    carimg: 'img/carscard/fifth.jpeg',
    engine: 'NCAP: 5*',
    fuel: 'Petrol CNG Diesel',
    drivetype: 'Manual IMT DCT IVT',
    carname: 'Tuscon',
    noofseats: '5 ',
  ),
  CarsDataCard(
    price: '1.04',
    carimg: 'img/carscard/fifth.jpeg',
    engine: 'NCAP: 5*',
    fuel: 'Petrol CNG Diesel',
    drivetype: 'Manual IMT DCT IVT',
    carname: 'Tuscon',
    noofseats: '5 ',
  ),
  CarsDataCard(
    price: '1.04',
    carimg: 'img/carscard/fifth.jpeg',
    engine: 'NCAP: 5*',
    fuel: 'Petrol CNG Diesel',
    drivetype: 'Manual IMT DCT IVT',
    carname: 'Tuscon',
    noofseats: '5 ',
  ),
  CarsDataCard(
    price: '1.04',
    carimg: 'img/carscard/fifth.jpeg',
    engine: 'NCAP: 5*',
    fuel: 'Petrol CNG Diesel',
    drivetype: 'Manual IMT DCT IVT',
    carname: 'Tuscon',
    noofseats: '5 ',
  ),
  CarsDataCard(
    price: '1.04',
    carimg: 'img/carscard/fifth.jpeg',
    engine: 'NCAP: 5*',
    fuel: 'Petrol CNG Diesel',
    drivetype: 'Manual IMT DCT IVT',
    carname: 'Tuscon',
    noofseats: '5 ',
  ),
  CarsDataCard(
    price: '1.04',
    carimg: 'img/carscard/fifth.jpeg',
    engine: 'NCAP: 5*',
    fuel: 'Petrol CNG Diesel',
    drivetype: 'Manual IMT DCT IVT',
    carname: 'Tuscon',
    noofseats: '5 ',
  ),
];

List<CarsDataCard> _underA50 = [
  CarsDataCard(
    price: '1.04',
    carimg: 'img/carscard/sixth.jpeg',
    engine: 'NCAP: 5*',
    fuel: 'Petrol CNG Diesel',
    drivetype: 'Manual IMT DCT IVT',
    carname: 'Tuscon',
    noofseats: '5 ',
  ),
  CarsDataCard(
    price: '1.04',
    carimg: 'img/carscard/sixth.jpeg',
    engine: 'NCAP: 5*',
    fuel: 'Petrol CNG Diesel',
    drivetype: 'Manual IMT DCT IVT',
    carname: 'Tuscon',
    noofseats: '5 ',
  ),
  CarsDataCard(
    price: '1.04',
    carimg: 'img/carscard/sixth.jpeg',
    engine: 'NCAP: 5*',
    fuel: 'Petrol CNG Diesel',
    drivetype: 'Manual IMT DCT IVT',
    carname: 'Tuscon',
    noofseats: '5 ',
  ),
  CarsDataCard(
    price: '1.04',
    carimg: 'img/carscard/sixth.jpeg',
    engine: 'NCAP: 5*',
    fuel: 'Petrol CNG Diesel',
    drivetype: 'Manual IMT DCT IVT',
    carname: 'Tuscon',
    noofseats: '5 ',
  ),
  CarsDataCard(
    price: '1.04',
    carimg: 'img/carscard/sixth.jpeg',
    engine: 'NCAP: 5*',
    fuel: 'Petrol CNG Diesel',
    drivetype: 'Manual IMT DCT IVT',
    carname: 'Tuscon',
    noofseats: '5 ',
  ),
  CarsDataCard(
    price: '1.04',
    carimg: 'img/carscard/sixth.jpeg',
    engine: 'NCAP: 5*',
    fuel: 'Petrol CNG Diesel',
    drivetype: 'Manual IMT DCT IVT',
    carname: 'Tuscon',
    noofseats: '5 ',
  ),
  CarsDataCard(
    price: '1.04',
    carimg: 'img/carscard/sixth.jpeg',
    engine: 'NCAP: 5*',
    fuel: 'Petrol CNG Diesel',
    drivetype: 'Manual IMT DCT IVT',
    carname: 'Tuscon',
    noofseats: '5 ',
  ),
];
