// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3_sY0-ad1rJ4WIKxrmCV7qjRhIOX-0FQ',
    appId: '1:90193307871:web:d5eff7014af3f9a2d2a16a',
    messagingSenderId: '90193307871',
    projectId: 'motoroctane-9e421',
    authDomain: 'motoroctane-9e421.firebaseapp.com',
    storageBucket: 'motoroctane-9e421.appspot.com',
    measurementId: 'G-YK9RH7VXV2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbmLjj6UIrTfFgaSe2fChr5o7C_AnY2yo',
    appId: '1:90193307871:android:7e49ecb34859fdd9d2a16a',
    messagingSenderId: '90193307871',
    projectId: 'motoroctane-9e421',
    storageBucket: 'motoroctane-9e421.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZ3NCuyd-WidAkvFEJ1CnMuARHIeGvwhs',
    appId: '1:90193307871:ios:a16be62f5c11e55fd2a16a',
    messagingSenderId: '90193307871',
    projectId: 'motoroctane-9e421',
    storageBucket: 'motoroctane-9e421.appspot.com',
    iosClientId: '90193307871-d81k02glcj54e630o717heoejdgkpgq1.apps.googleusercontent.com',
    iosBundleId: 'com.example.review',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZ3NCuyd-WidAkvFEJ1CnMuARHIeGvwhs',
    appId: '1:90193307871:ios:7ff8afca85093104d2a16a',
    messagingSenderId: '90193307871',
    projectId: 'motoroctane-9e421',
    storageBucket: 'motoroctane-9e421.appspot.com',
    iosClientId: '90193307871-5fj30uujcuqphacinuk58njh60ceigsg.apps.googleusercontent.com',
    iosBundleId: 'com.example.review.RunnerTests',
  );
}
